name: my first CICD workflows

on: push

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: we are testing
        run: echo Hello!!

