version: '3.8'

services:
  web:
  image: 
    build: 038462785413.dkr.ecr.eu-west-2.amazonaws.com/flask-mysql:latest      
    ports:
      - "5002:5002"
    depends_on:
      - mydb

  mydb:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw